
name: Deploy Azure Function App

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove Terraform cache
        run: rm -rf .terraform .terraform.lock.hcl

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  

      # ----------------------
      # Install & Run TFLint
      # ----------------------
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Run TFLint
        run: tflint
        continue-on-error: true

      # ----------------------
      # Install & Run tfsec
      # ----------------------
      - name: Install tfsec
        run: |
          curl -sSL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

      - name: Run tfsec
        run: tfsec .
        continue-on-error: true

      # ----------------------
      # Install & Run Terrascan
      # ----------------------
      - name: Install Terrascan
        run: |
          curl -sSL https://github.com/tenable/terrascan/releases/latest/download/terrascan_Linux_x86_64 -o terrascan
          chmod +x terrascan
          sudo mv terrascan /usr/local/bin/

      - name: Run Terrascan
        run: terrascan scan -t azure -i terraform
        continue-on-error: true

      # ----------------------
      # Install & Run Checkov
      # ----------------------
      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d .
        continue-on-error: true

      # ----------------------
      # Terraform Steps
      # ----------------------
      - name: Terraform Init (with upgrade)
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

